// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for automated entity enrichment.
 *
 * The flow takes a text input and enriches it with relevant information about
 * people, organizations, and sites using GenAI.
 *
 * @file        automated-entity-enrichment.ts
 * @exports   automatedEntityEnrichment
 * @exports   AutomatedEntityEnrichmentInput
 * @exports   AutomatedEntityEnrichmentOutput
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the automated entity enrichment flow.
const AutomatedEntityEnrichmentInputSchema = z.object({
  text: z.string().describe('The text to analyze and enrich with entity data.'),
});

// Define the output schema for the automated entity enrichment flow.
const AutomatedEntityEnrichmentOutputSchema = z.object({
  enrichedText: z
    .string()
    .describe('The text enriched with relevant entity information.'),
});

// Define the input and output types based on the schemas.
export type AutomatedEntityEnrichmentInput = z.infer<
  typeof AutomatedEntityEnrichmentInputSchema
>;
export type AutomatedEntityEnrichmentOutput = z.infer<
  typeof AutomatedEntityEnrichmentOutputSchema
>;

// Define the automated entity enrichment flow.
const automatedEntityEnrichmentFlow = ai.defineFlow(
  {
    name: 'automatedEntityEnrichmentFlow',
    inputSchema: AutomatedEntityEnrichmentInputSchema,
    outputSchema: AutomatedEntityEnrichmentOutputSchema,
  },
  async input => {
    // Call the prompt to enrich the text with entity data.
    const {output} = await automatedEntityEnrichmentPrompt(input);
    // Return the enriched text.
    return output!;
  }
);

// Define the prompt for automated entity enrichment.
const automatedEntityEnrichmentPrompt = ai.definePrompt({
  name: 'automatedEntityEnrichmentPrompt',
  input: {schema: AutomatedEntityEnrichmentInputSchema},
  output: {schema: AutomatedEntityEnrichmentOutputSchema},
  prompt: `You are an AI assistant designed to enrich text with relevant entity information.

  Your task is to analyze the given text and identify people, organizations, and sites mentioned within it.
  Then, enrich the text by adding relevant details about these entities, such as their descriptions, relationships, and other pertinent information.

  Text to analyze:
  {{text}}`,
});

/**
 * Enriches the input text with relevant entity information using GenAI.
 *
 * @param input - The input object containing the text to enrich.
 * @returns A promise that resolves to the enriched text.
 */
export async function automatedEntityEnrichment(
  input: AutomatedEntityEnrichmentInput
): Promise<AutomatedEntityEnrichmentOutput> {
  return automatedEntityEnrichmentFlow(input);
}
