// This is an autogenerated file from Firebase Studio.
'use server';

import * as cheerio from 'cheerio';

/**
 * @fileOverview A service for web scraping using fetch and cheerio.
 */

/**
 * Fetches and scrapes a web page to extract its text content.
 *
 * @param url - The URL of the page to scrape.
 * @param cookies - Optional cookies to include in the request for authenticated sessions.
 * @returns A promise that resolves to the text content of the page, or null if fetching fails.
 */
export async function scrapeWebPage(
  url: string,
  cookies?: string
): Promise<string | null> {
  console.log(`[ScrapingService] Starting scrape for URL: ${url}`);

  try {
    const headers: HeadersInit = {
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    };
    if (cookies) {
      headers['Cookie'] = cookies;
    }

    const response = await fetch(url, { headers });

    if (!response.ok) {
      console.error(
        `[ScrapingService] Failed to fetch ${url}. Status: ${response.status}`
      );
      return null;
    }

    const html = await response.text();
    const $ = cheerio.load(html);

    // Remove script and style tags to clean up the text
    $('script, style, noscript, iframe, svg, header, footer, nav, aside').remove();

    // Get text from the body, trying to preserve some structure with newlines
    let text = $('body').text() || '';

    // Basic cleanup
    text = text
      .replace(/\s\s+/g, ' ') // Replace multiple spaces with a single space
      .replace(/\n\s*\n/g, '\n') // Replace multiple newlines with a single one
      .trim();
      
    console.log(`[ScrapingService] Successfully scraped ${text.length} characters from ${url}.`);

    return text;
  } catch (error: any) {
    console.error(`[ScrapingService] Error during scraping for ${url}:`, error);
    return null;
  }
}
